[project]
authors = ["Daniel Knüttel"]

description = "empty"
platforms = "any"
dependencies = []

[build-system]
requires = ["meson", "mesonpep517"]
build-backend = "mesonpep517.buildapi"

[tool.mesonpep517.metadata]
summary = "test"

